#+TITLE: The Greatest Sales Deck I've Ever Seen
#+YEAR: 2016
#+URL: https://medium.com/the-mission/the-greatest-sales-deck-ive-ever-seen-4f4ef3391ba0#.wl1don9d6
#+TAGS: sales marketing business startups

* 5 Elements of a Brilliant Sales Narrative
** 1. Name a Big, Relevant Change in the World
Name undeniable shift in the world that creates (a) big stakes and (b)
urgency for your proposition

Ex: "We now live in a subscription economy", "We are now living in a
different era"

Change is attention grabbing, interesting
** 2. Show There'll Be Winners and Losers
Loss aversion: avoiding a possible loss by sticking to status quo
rather than risking gain by opting for change

Show:

1. Adapting to change will result in positive future
2. Not adapting is unacceptaby risky
** 3. Tease the Promised Land
Don't jump into details about product. Tease the audience about the
happily ever after vision.

Promised Land should be desirable and difficult to achieve without
outside help (your offering).
** 4. Introduce Features as "Magic Gifts" for Overcoming Obstacles
** 5. Present Evidence You Can Make the Story Come True
"Come with us, we'll take you to the Promised Land."

Prospects will be skeptical, so provide evidence to calm that
skepticism.

- Tell a success story about how you helped someone
else
  - Recommendations from satisfied customers are great
- Product demos are fine too
  - Remember, sell features not products

* Everyone on the Team Should Use the Narrative
