#+TITLE: Moral Letters to Lucilius
#+AUTHOR: Seneca
#+YEAR: 65-69?
#+TAGS: philosophy seneca stoicism

* On Saving Time
"For we are mistaken when we look look forward to death; the major
portion of death has already passed. Whatever years be behind us are
in death's hands."

"...hold every hour in your grasp. Lay hold of to-day's task, and you
will not need to depend so much upon to-morrow's. While we are
postponing, life speeds by. Nothing, Lucilius, is ours, except time."

"I do not regard a man as poor, if the little which remains is enough for him."
* On Discursiveness in Reading
"The primary indication, to my thinking, of a well-ordered mind is a
man's ability to remain in one place and linger in his own company."

"Everywhere means nowhere. When a person spends all his time in
foreign travel, he ends by having many acquaintances, but no friends."

Reading many books, like taking many medicines for a short period or
making temporary acquaintances, is not effective. One must focus intimately.

"Each day acqurie something that will fortify you against poverty,
against death, indeed against other misfortunes as well...select one
to be thoroughly digested that day."

"Contented poverty is an honourable estate." Indeed, if it be
contented, it is not poverty at all. It is not the man who has too
little, but the man who craves more, that is poor. What does it matter
how much a man h as laid up in his safe, or in his warehouse, how large are
his flocks and how fat his dividends, if he covets his neighbour's
property, and reckons, not his past gains, but his hopes of gains to
come? Do you ask what is the proper limit to wealth? It is, first, to
have what is necessary, and, second, to have what is enough. Farewell."
* On True and False Friendship
"But if you consider any man a friend whom you do not trust as you
trust yourself, you are mightily mistaken and you do not sufficiently
understand what true friendship means."

"When friendship is settled, you must trust; before friendship is
formed, you must pass judgment...Ponder for a long time whether you
shall admit a given person to your friendship; but when you have
decided to admit him, welcome him with all your heart and soul. Speak as boldly
with him as with yourself."

"As to yourself, although you should live in such a way that you trust
your own self with nothing which you could not entrust even to your
enemy, yet, since certain matters occur which convention keeps secret,
you should share with a friend at least all your worries and
reflections. Regard him as loyal, and you will make him loyal. Some,
for example, fearing to be deceived, have taught men to deceive; by
their suspicions they have given their friend the right to do
wrong. Why need I keep back any words in the presence of my friend? Why should I
not regard myself as alone when in his company?"

"In like manner you should rebuke these two kinds of men, – both those
who always lack repose, and those who are always in repose. For love
of bustle is not industry, – it is only the restlessness of a hunted
mind. And true repose does not consist in condemning all motion as
merely vexation; that kind of repose is slackness and
inertia. 6. Therefore, you should note the following saying, taken
from my reading in Pomponius:[3] "Some men shrink into dark corners,
to such a degree that they see darkly by day." No, men should combine
these tendencies, and he who reposes should act and he who acts should
take repose. Discuss the problem with Nature; she will tell you that
she has created both day and night."
* On the Terrors of Death
"...since the day you were born you are being led thither. We must
ponder this thought, and thoughts of the like nature, if we desire to
be calm as we await that last hour, the fear of which makes all
previous hours uneasy."

"It is the superfluous things for which men sweat, – the superfluous
things that wear our togas threadbare, that force us to grow old in
camp, dash us upon foreign shores. That which is enough is ready to
our hands. He who  made a fair compact with poverty is rich."
*  On the Philosopher's Mean
Our outward appearance should be modest, but blend in with
society. But our inside must be remarkable, a stand out.

This relects my approach to minimalism: -tbv

"Do not wear too fine, nor yet too frowzy, a toga. One needs no silver
plate, encrusted and embossed in solid gold; but we should not believe
the lack of silver and gold to be proof of the simple life. Let us try
to maintain a higher standard of life than that of the multitude, but
not  a contrary standard; otherwise, we shall frighten away and repel
the very persons whom we are trying to improve. We also bring it about
that they are unwilling to imitate us in anything, because they are
afraid lest they might be compelled to imitate us in everything."


"Just as it is a sign of luxury to seek out dainties, so it is madness
to avoid that which is customary and can be purchased at no great
price. Philosophy calls for plain living, but not for penance; and we
may perfectly well be plain and neat at the same time. This is the
mean of which I approve; our life should observe a happy medium
between the ways of a sage and the ways of the world at large; all men
should admire it, but they should understand it also."
* On Sharing Knowledge
"I can show you many who have lacked, not a friend, but a friendship;
this, however, cannot possibly happen when souls are drawn together by
identical inclinations into an alliance of honourable desires. And why
can it not happen? Because in such cases men know that they have all
things in common, especially their troubles.

You cannot conceive what distinct progress I notice that each day
brings to me. 4. And when you say: "Give me also a share in these
gifts which you have found so helpful," I reply that I am anxious to
heap all these privileges upon you, and that I am glad to learn in
order that I may teach. Nothing will ever please me, no matter how
excellent or beneficial, if I must retain the knowledge of it to
myself. And if wisdom were given me under the express condition that
it must be kept hidden and not uttered, I should refuse it. No good
thing is pleasant to possess, without friends to share it."
* On Crowds
"To consort with the crowd is harmful; there is no person who does not
make some vice attractive to us, or stamp it upon us, or taint us
unconsciously therewith. Certainly, the greater the mob with which
we mingle, the greater the danger."

"But both courses are to be avoided; you should not copy the bad
simply because they are many, nor should you hate the many because
they are unlike you. Withdraw into yourself, as far as you
can. Associate with those who will make a better man of you. Welcome
those whom you yourself can improve. The process is mutual; for men
learn while they teach."
* On the Philosopher's Seclusion
"Do you bid me," you say, "shun the throng, and withdraw from men,
and be content with my own conscience? Where are the counsels of your
school, which order a man to die in the midst of active work?" As to
the course[1] which I seem to you to be urging on you now and then, my
object in shutting myself up and locking the door is to be able to
help a greater number. I never spend a day in idleness; I appropriate
even a part of the night for study. I do not allow time for sleep but
yield to it when I must, and when my eyes are wearied with waking
and ready to fall shut, I keep them at their task. 2. I have withdrawn
not only from men,but from affairs, especially from my own affairs; I
am working for later generations, writing down some ideas that may
be of assistance to them. There are certain wholesome counsels,
which may be compared to prescriptions of useful drugs; these I am
putting into writing; for I have found them helpful in ministering to
my own sores, which, if not wholly cured, have at any rate ceased to spread."
